package com.technology.jep.jepriashowcase.feature.client;

public class FeatureAutomationConstant {
  /**
   * Идентификаторы полей детальной формы
   */
  public static final String FEATURE_FEATUREID_DETAILFORM_FIELD_ID = "FEATURE_FEATUREID_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURENAME_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAME_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAMEEN_DETAILFORM_FIELD";
  public static final String FEATURE_WORKSEQUENCEFROM_DETAILFORM_FIELD_ID = "FEATURE_WORKSEQUENCEFROM_DETAILFORM_FIELD";
  public static final String FEATURE_WORKSEQUENCETO_DETAILFORM_FIELD_ID = "FEATURE_WORKSEQUENCETO_DETAILFORM_FIELD";
  public static final String FEATURE_WORKSEQUENCE_DETAILFORM_FIELD_ID = "FEATURE_WORKSEQUENCE_DETAILFORM_FIELD";
  public static final String FEATURE_FROMDATEINS_DETAILFORM_FIELD_ID = "FEATURE_FROMDATEINS_DETAILFORM_FIELD";
  public static final String FEATURE_TODATEINS_DETAILFORM_FIELD_ID = "FEATURE_TODATEINS_DETAILFORM_FIELD";
  public static final String FEATURE_DESCRIPTION_DETAILFORM_FIELD_ID = "FEATURE_DESCRIPTION_DETAILFORM_FIELD";
  public static final String FEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID = "FEATURE_MAXROWCOUNT_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURE_STATUS_NAME_FIELD_ID = "FEATURE_FEATURE_STATUS_NAME_FIELD";

  public static final String FEATURE_FEATURE_STATUS_CODE_DETAILFORM_FIELD_ID = "FEATURE_FEATURE_STATUS_CODE_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURE_STATUS_CODE_LIST_DETAILFORM_FIELD_ID = "FEATURE_FEATURE_STATUS_CODE_LIST_DETAILFORM_FIELD";
  public static final String FEATURE_AUTHOR_ID_DETAILFORM_FIELD_ID = "FEATURE_AUTHOR_ID_DETAILFORM_FIELD";
  public static final String FEATURE_RESPONSIBLE_ID_DETAILFORM_FIELD_ID = "FEATURE_RESPONSIBLE_ID_DETAILFORM_FIELD";

  public static final String FEATURE_GRID_ID = "featureGrid";
}
